name: AKS Store CI/CD Pipeline

on:
  # push:
  #   branches: [ main, develop ]
  # pull_request:
  #   branches: [ main ]
  # release:
  #   types: [published]
  workflow_dispatch:


env:
  NODE_VERSION: '22.x'
  WORKING_DIRECTORY: './src/store-front'


jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: ${{ env.WORKING_DIRECTORY }}/package-lock.json
      
    - name: Install dependencies
      run: npm install
      working-directory: ${{ env.WORKING_DIRECTORY }}
    - name: Run linting
      run: |
        if npm run lint --if-present; then
          echo "Linting passed"
        else
          echo "No lint script found or linting failed"
          exit 0
        fi
    - name: Run unit tests
      run: |
        if npm run test:unit --if-present; then
          echo "Unit tests passed"
        elif npm run test --if-present; then
          echo "Tests passed"
        else
          echo "No test script found"
        fi
    - name: Build application
      run: npm run build
      env:
        VUE_APP_PRODUCT_SERVICE_URL: ${{ vars.VUE_APP_PRODUCT_SERVICE_URL || 'http://product-service:3002' }}
        VUE_APP_ORDER_SERVICE_URL: ${{ vars.VUE_APP_ORDER_SERVICE_URL || 'http://order-service:3000' }}
      working-directory: ${{ env.WORKING_DIRECTORY }}
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}-store-front-dist-${{ github.run_number }}
        path: ${{ env.WORKING_DIRECTORY }}/dist/**/*
        retention-days: 30
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ github.event.repository.name }}-store-front-test-results-${{ github.run_number }}
        path: |
          ${{ env.WORKING_DIRECTORY }}/coverage/**/*
          ${{ env.WORKING_DIRECTORY }}/test-results/**/*
        retention-days: 30
